import { NextResponse } from "next/server";
import { bigScaleChapters } from "../chapters";

const assetBase = "/big-scale-betrayal/assets";

type ChapterMedia = {
  after: number;
  alt?: string;
  caption: string;
  chapterNumber: number;
  src: string;
  type: "image" | "video";
  wide?: boolean;
};

const chapterMedia: ChapterMedia[] = [
  {
    chapterNumber: 1,
    after: 2,
    type: "image",
    src: `${assetBase}/chapter1-royal-guardian.png`,
    alt: "The armored crocodile guardian watches the royal library steps of Kemet",
    caption: "The armored guardian of the royal library of Kemet, bells at its throat, incense at its brow.",
    wide: true,
  },
  {
    chapterNumber: 1,
    after: 3,
    type: "image",
    src: `${assetBase}/chapter1-heba-amunet.png`,
    alt: "Heba holds a cabbage beside Amunet at their crowded market stall",
    caption: "Amunet weighs love against debt while Heba keeps her hands on the cabbages.",
    wide: true,
  },
  {
    chapterNumber: 1,
    after: 14,
    type: "image",
    src: `${assetBase}/chapter1-namoot-crystal.png`,
    alt: "Namoot offers a glowing amethyst crystal to Heba at the cabbage stall while Amunet watches",
    caption: "Namoot brings the amethyst close, and the spirits enter the stall before Heba can name them.",
    wide: true,
  },
  {
    chapterNumber: 1,
    after: 20,
    type: "image",
    src: `${assetBase}/market.png`,
    alt: "Heba and a young thief near a cabbage stall in the market of Kemet",
    caption: "The market of Kemet, the hour before the chase.",
    wide: true,
  },
  {
    chapterNumber: 1,
    after: 37,
    type: "image",
    src: `${assetBase}/chapter1-feather-sun.png`,
    alt: "Namoot throws Amunet's white feather into the blazing red sun above the market",
    caption: "Namoot throws the feather, and the sun counts five circles before returning it.",
    wide: true,
  },
  {
    chapterNumber: 3,
    after: 2,
    type: "image",
    src: `${assetBase}/chapter3-image-1.png`,
    alt: "Heba and Amunet watch Sate arrive in a sandstorm between two armored crocodiles in the Kemet market",
    caption: "Sate rises from the sand, and Matu and Nefer turn the market toward judgment.",
    wide: true,
  },
  {
    chapterNumber: 3,
    after: 9,
    type: "image",
    src: `${assetBase}/chapter3-image-4.png`,
    alt: "Heba studies her glowing scale with a white feather and living red heart in the quiet of the cabbage stall",
    caption: "Heba watches the heart beat and the feather burn, understanding that the scale is still speaking.",
    wide: true,
  },
  {
    chapterNumber: 3,
    after: 41,
    type: "image",
    src: `${assetBase}/chapter3-image-2.png`,
    alt: "Prince Ahmose rises from a wave of dark red wine while Sate lies defeated in the market",
    caption: "Ahmose steps out of the wine, and the marketplace learns another kind of power has arrived.",
    wide: true,
  },
  {
    chapterNumber: 3,
    after: 78,
    type: "image",
    src: `${assetBase}/chapter3-image-3.png`,
    alt: "A translucent ice hawk spreads its wings before Heba, Amunet, and the crocodile guardians in the Kemet market",
    caption: "Water becomes a hawk of ice, and Heba sees Heka answer in public.",
    wide: true,
  },
  {
    chapterNumber: 4,
    after: 1,
    type: "image",
    src: `${assetBase}/chapter4-heba-wakes-palace.png`,
    alt: "Heba wakes on an ornate palace bed beneath gold chandeliers and murals of the gods",
    caption: "Heba wakes beneath gold and god-murals, far from the cabbage stall.",
    wide: true,
  },
  {
    chapterNumber: 4,
    after: 10,
    type: "image",
    src: `${assetBase}/chapter4-queen-of-kemet.png`,
    alt: "The Queen of Kemet extends her hand in a golden palace chamber",
    caption: "The great royal wife offers her hand, and the palace names her queen.",
    wide: true,
  },
  {
    chapterNumber: 4,
    after: 59,
    type: "image",
    src: `${assetBase}/chapter4-tawet-seket-rift.png`,
    alt: "Tawet conjures a cloud while Seket steps through a golden rift beside Heba in the palace",
    caption: "Tawet shows off, Seket tears through the air, and Heba lands on a cloud.",
    wide: true,
  },
  {
    chapterNumber: 4,
    after: 71,
    type: "image",
    src: `${assetBase}/chapter4-pharaoh-of-kemet.png`,
    alt: "The Pharaoh of Kemet appears in gold light while attendants bow in the palace",
    caption: "The Pharaoh gathers himself from black sand, and the room remembers how to kneel.",
    wide: true,
  },
  {
    chapterNumber: 5,
    after: 4,
    type: "image",
    src: `${assetBase}/chapter5-pharaoh-conjures-cat.png`,
    alt: "The Pharaoh conjures a smoky rainbow cat onto Heba's shoulder in the palace",
    caption: "The Pharaoh gives smoke weight, and Heba learns the palace can make wonder feel like command.",
    wide: true,
  },
  {
    chapterNumber: 5,
    after: 24,
    type: "image",
    src: `${assetBase}/chapter5-heba-meets-aken.png`,
    alt: "Heba faces Prince Aken as shadowy Heka gathers behind him in the palace",
    caption: "Aken arrives with a darker silence, and Heba feels another royal heart enter the room.",
    wide: true,
  },
  {
    chapterNumber: 5,
    after: 41,
    type: "image",
    src: `${assetBase}/chapter5-heba-dreams-unity.png`,
    alt: "Heba stands between the royal family as golden light connects them in the palace",
    caption: "The royal family closes around Heba, beautiful as a promise and dangerous as a lock.",
    wide: true,
  },
  {
    chapterNumber: 5,
    after: 68,
    type: "image",
    src: `${assetBase}/chapter5-ahmose-ice-flower.png`,
    alt: "Ahmose conjures a delicate ice flower between himself and Heba in the palace",
    caption: "Ahmose turns tears into ice, and the flower between them says what neither can afford to name.",
    wide: true,
  },
  {
    chapterNumber: 6,
    after: 23,
    type: "image",
    src: `${assetBase}/chapter6-mata-first-lesson.png`,
    alt: "Mata sits with Heba and a black jackal beside an old linen strip painted with a scale",
    caption: "Mata sets the first lesson between them, old linen holding a truth Heba has already seen.",
    wide: true,
  },
  {
    chapterNumber: 6,
    after: 81,
    type: "image",
    src: `${assetBase}/chapter6-black-sand-trace.png`,
    alt: "Mata, Heba, and a black jackal find glittering black sand before the royal throne",
    caption: "The jackal finds black sand before the throne, and the palace loses another layer of gold.",
    wide: true,
  },
  {
    chapterNumber: 6,
    after: 160,
    type: "image",
    src: `${assetBase}/chapter6-ahmose-doorway.png`,
    alt: "Ahmose raises his hands in the palace doorway while Heba, Mata, and the jackal watch him",
    caption: "Ahmose enters with empty hands, inked nails, and a silence Heba cannot weigh.",
    wide: true,
  },
  {
    chapterNumber: 6,
    after: 294,
    type: "image",
    src: `${assetBase}/chapter6-scale-heart-beats.png`,
    alt: "Heba holds the old linen scale as the painted heart glows red in her hands",
    caption: "The lesson warms in Heba's hands, and the painted heart begins to beat.",
    wide: true,
  },
  {
    chapterNumber: 7,
    after: 12,
    type: "image",
    src: `${assetBase}/chapter7-copper-corridor.png`,
    alt: "Heba, Mata, Ahmose, the jackal, and crocodile guardians move through a copper-lined palace corridor",
    caption: "The corridor narrows, the pots watch, and even the crocodiles know where not to follow.",
    wide: true,
  },
  {
    chapterNumber: 7,
    after: 32,
    type: "image",
    src: `${assetBase}/chapter7-duna-kitchen-ghost.png`,
    alt: "The golden spirit of Duna kneads bread before Heba, Mata, and the jackal in the palace kitchen",
    caption: "Duna sings without a heartbeat, and the kitchen remembers a man the palace forgot to ask about.",
    wide: true,
  },
  {
    chapterNumber: 7,
    after: 53,
    type: "image",
    src: `${assetBase}/chapter7-mata-golden-word.png`,
    alt: "Mata raises one hand as golden Heka spirals over a honey-cake trace in the palace kitchen",
    caption: "Mata spends one word, the loaves sink, and the trap leaves a honey-cake shape behind.",
    wide: true,
  },
  {
    chapterNumber: 7,
    after: 93,
    type: "image",
    src: `${assetBase}/chapter7-threshold-scale.png`,
    alt: "Heba kneels with a lamp before a black-sand scale drawn across a palace threshold",
    caption: "At the threshold, black sand writes Heba's name and draws the shape that has been following her.",
    wide: true,
  },
  {
    chapterNumber: 8,
    after: 15,
    type: "image",
    src: `${assetBase}/chapter8-userhat-trainees.png`,
    alt: "Userhat stands before a line of temple trainees while Heba watches in the hall of trials",
    caption: "Userhat walks the line of trainees, and Heba learns the hall of trials has already begun weighing her.",
    wide: true,
  },
  {
    chapterNumber: 8,
    after: 20,
    type: "image",
    src: `${assetBase}/chapter8-chamber-revealed.png`,
    alt: "Heba and the trainees stand before the vast golden chamber of judgment beneath the western temple",
    caption: "The far wall opens, and the chamber of judgment reveals a floor that is already paying attention.",
    wide: true,
  },
  {
    chapterNumber: 8,
    after: 34,
    type: "image",
    src: `${assetBase}/chapter8-heba-crosses-sand.png`,
    alt: "Heba walks alone across the glowing sand floor of the chamber of judgment",
    caption: "Heba steps onto the sand alone, and the floor begins to ask what she is made of.",
    wide: true,
  },
  {
    chapterNumber: 9,
    after: 4,
    type: "image",
    src: `${assetBase}/chapter9-cat-no-shadow.png`,
    alt: "Heba writes notes in a palace doorway while a gray cat with no shadow watches from the sunlit ledge",
    caption: "Heba keeps a ledger of small lies, and the cat with no shadow makes the page heavier.",
    wide: true,
  },
  {
    chapterNumber: 9,
    after: 12,
    type: "image",
    src: `${assetBase}/chapter9-blue-flames-corridor.png`,
    alt: "Userhat presents a corridor lit by blue flames to Heba, Pharaoh, and the remaining trainees",
    caption: "Userhat names the second trial, and the corridor answers in blue fire.",
    wide: true,
  },
  {
    chapterNumber: 9,
    after: 24,
    type: "image",
    src: `${assetBase}/chapter9-hall-borrowed-voices.png`,
    alt: "Heba walks through the dark Hall of Borrowed Voices as golden and silver smoke takes shape around her",
    caption: "Inside the sealed dark, borrowed voices gather close enough to touch.",
    wide: true,
  },
  {
    chapterNumber: 9,
    after: 53,
    type: "image",
    src: `${assetBase}/chapter9-emergence-far-door.png`,
    alt: "Heba emerges from the far door of the Hall of Borrowed Voices while Userhat and attendants look up in shock",
    caption: "Heba reaches the far door with her own feet, and the watching hall has to record it.",
    wide: true,
  },
  {
    chapterNumber: 10,
    after: 25,
    type: "image",
    src: `${assetBase}/chapter10-rooftop-evening.png`,
    alt: "Heba and Ahmose sit on a palace rooftop above the moonlit Nile with market food between them",
    caption: "One evening, the rooftop lets them be seventeen before the palace remembers its teeth.",
    wide: true,
  },
  {
    chapterNumber: 10,
    after: 39,
    type: "image",
    src: `${assetBase}/chapter10-house-of-learning-stars.png`,
    alt: "Ahmose points to a star-drawn house of learning above Kemet as Heba watches beside him",
    caption: "Ahmose sketches a house with no locks, and the stars hold the shape for one breath.",
    wide: true,
  },
  {
    chapterNumber: 10,
    after: 65,
    type: "image",
    src: `${assetBase}/chapter10-mirror-warning.png`,
    alt: "Heba faces a bronze mirror where Ahmose's reflection raises a finger to its lips while the real prince walks away",
    caption: "The bronze keeps smiling after the boy has gone.",
    wide: true,
  },
  {
    chapterNumber: 11,
    after: 2,
    type: "image",
    src: `${assetBase}/chapter11-mata-blue-mortar.png`,
    alt: "Heba watches Mata grind blue powder in her workroom while the black jackal rests in the doorway",
    caption: "Mata grinds the blue warning, and the third trial waits until the honest hour.",
    wide: true,
  },
  {
    chapterNumber: 11,
    after: 9,
    type: "image",
    src: `${assetBase}/chapter11-heart-trial-dream.png`,
    alt: "Heba sleeps as golden dream light opens from the palace room toward Kemet at dawn",
    caption: "The trial comes for Heba in sleep, wearing the life she wants most.",
    wide: true,
  },
  {
    chapterNumber: 11,
    after: 17,
    type: "image",
    src: `${assetBase}/chapter11-perfect-market.png`,
    alt: "Heba stands before a radiant dream-market cabbage stall where her family laughs in golden light",
    caption: "The market offers Heba a paid debt, a whole family, and a price hidden under honey light.",
    wide: true,
  },
  {
    chapterNumber: 11,
    after: 42,
    type: "image",
    src: `${assetBase}/chapter11-cosmic-scale.png`,
    alt: "Heba stands before a vast cosmic scale holding a white feather and a glowing heart among the stars",
    caption: "The true scale fills the dark, and Heba learns the palace has only ever held a shadow of it.",
    wide: true,
  },
  {
    chapterNumber: 12,
    after: 4,
    type: "image",
    src: `${assetBase}/chapter12-festival-road.png`,
    alt: "Heba stands at the flood festival beside a stall selling braided hair extensions, gold rings, and river offerings",
    caption: "At the flood festival, Heba finds her own designs laid out in someone else's rows.",
    wide: true,
  },
  {
    chapterNumber: 12,
    after: 16,
    type: "image",
    src: `${assetBase}/chapter12-match-day-courtyard.png`,
    alt: "Heba stands alone in the raked sand of the Match Day courtyard before the royal family and crocodile guardians",
    caption: "Match Day gathers the royal family, the crocodiles, and every eye that wants Heba named.",
    wide: true,
  },
  {
    chapterNumber: 12,
    after: 36,
    type: "image",
    src: `${assetBase}/chapter12-sand-scale-overhead.png`,
    alt: "An overhead view of the Match Day courtyard as the raked sand forms a vast sacred scale around Heba",
    caption: "The sand answers Userhat and draws the scale large enough for all of Kemet to see.",
    wide: true,
  },
  {
    chapterNumber: 12,
    after: 84,
    type: "image",
    src: `${assetBase}/chapter12-book-of-the-broken.png`,
    alt: "The Book of the Broken lies hidden inside a bronze tray as a hand reaches toward it in a torchlit palace corridor",
    caption: "The tray opens, the flames pull back, and the planted book finally shows its teeth.",
    wide: true,
  },
  {
    chapterNumber: 13,
    after: 2,
    type: "image",
    src: `${assetBase}/chapter13-descent-to-cells.png`,
    alt: "Heba descends wet stone stairs toward the cells carrying Nahara's faceless doll",
    caption: "Heba carries the doll below the festival noise, toward the door Sate thought would stop her.",
    wide: true,
  },
  {
    chapterNumber: 13,
    after: 8,
    type: "image",
    src: `${assetBase}/chapter13-iron-door-guards.png`,
    alt: "Heba faces two guards before a massive iron cell door in a torchlit prison corridor",
    caption: "Two guards learn the Fifth Judgment is not a title they want tested.",
    wide: true,
  },
  {
    chapterNumber: 13,
    after: 13,
    type: "image",
    src: `${assetBase}/chapter13-straight-cell.png`,
    alt: "Nahara's empty cell with squared straw, aligned sandals, and torchlight falling through the bars",
    caption: "Even in a cell, Nahara has squared the straw and lined up what little the palace left her.",
    wide: true,
  },
  {
    chapterNumber: 13,
    after: 80,
    type: "image",
    src: `${assetBase}/chapter13-two-taps-iron.png`,
    alt: "Heba presses her hand to the iron cell door while holding Nahara's faceless doll",
    caption: "Two taps on iron say what neither girl can afford to say aloud.",
    wide: true,
  },
  {
    chapterNumber: 14,
    after: 20,
    type: "image",
    src: `${assetBase}/chapter14-queen-magic-berserk.png`,
    alt: "The Queen of Kemet stands in the throne room as thorned vines overrun the walls and columns",
    caption: "The queen's magic shows what her perfect stillness has been holding back.",
    wide: true,
  },
  {
    chapterNumber: 14,
    after: 57,
    type: "image",
    src: `${assetBase}/chapter14-ahmose-winter-table.png`,
    alt: "Ahmose freezes the feast table and the people around him in the palace",
    caption: "Winter leaves Ahmose's hands and makes statues of everyone close enough to obey.",
    wide: true,
  },
  {
    chapterNumber: 14,
    after: 83,
    type: "image",
    src: `${assetBase}/chapter14-golden-judgment-doors.png`,
    alt: "Ancient golden judgment doors open against a star-filled dark",
    caption: "The door behind the family is not open yet, but the Glass has begun to show its shape.",
    wide: true,
  },
  {
    chapterNumber: 14,
    after: 94,
    type: "image",
    src: `${assetBase}/chapter14-black-sand-names.png`,
    alt: "Heba kneels with a lamp before six names written in black sand across her threshold",
    caption: "At Heba's door, black sand writes the ledger the palace buried.",
    wide: true,
  },
  {
    chapterNumber: 15,
    after: 3,
    type: "image",
    src: `${assetBase}/chapter15-jackals-at-sunrise.png`,
    alt: "Jackals watch the sunrise over Kemet and the flooded fields before the weighing",
    caption: "The sun rises early, and even the jackals go quiet before the weighing.",
    wide: true,
  },
  {
    chapterNumber: 15,
    after: 25,
    type: "image",
    src: `${assetBase}/chapter15-great-scale-stands.png`,
    alt: "The great scale fills the throne room as Heba stands before Ahmose and the royal family",
    caption: "The painted scale leaves the linen and becomes large enough to hold a dynasty.",
    wide: true,
  },
  {
    chapterNumber: 15,
    after: 56,
    type: "image",
    src: `${assetBase}/chapter15-ahmose-weigh-me.png`,
    alt: "Ahmose kneels before Heba beneath the suspended feather and heart plates",
    caption: "Ahmose asks for honest weight, with no thumb on the plate.",
    wide: true,
  },
  {
    chapterNumber: 15,
    after: 74,
    type: "image",
    src: `${assetBase}/chapter15-door-of-scales.png`,
    alt: "Heba stands before a vast radiant doorway filled with thousands of hanging scales",
    caption: "The wall opens, and the room where all ledgers are kept looks back.",
    wide: true,
  },
  {
    chapterNumber: 16,
    after: 10,
    type: "image",
    src: `${assetBase}/chapter16-duna-farewell.png`,
    alt: "Duna appears in golden spirit light before Ahmose as the dead pass through the doors",
    caption: "Duna gives the last line of the lullaby and walks into the light.",
    wide: true,
  },
  {
    chapterNumber: 16,
    after: 65,
    type: "image",
    src: `${assetBase}/chapter16-black-sarcophagus.png`,
    alt: "Heba lays her hand on a black sarcophagus carved with a scale while Mata and the jackal watch",
    caption: "Two taps return from the dark, small as rain.",
    wide: true,
  },
  {
    chapterNumber: 16,
    after: 80,
    type: "image",
    src: `${assetBase}/chapter16-heba-own-judgment.png`,
    alt: "Heba stands on the glowing plate of the great scale while the court kneels below",
    caption: "The bearer steps onto her own judgment at honest weight.",
    wide: true,
  },
  {
    chapterNumber: 16,
    after: 105,
    type: "image",
    src: `${assetBase}/chapter16-second-kiss.png`,
    alt: "Heba and Ahmose share their chosen second kiss before the opened doors",
    caption: "Her second kiss is chosen in the open, at honest weight.",
    wide: true,
  },
];

function wordCount() {
  return bigScaleChapters
    .flatMap((chapter) => chapter.paragraphs)
    .join(" ")
    .split(/\s+/)
    .filter(Boolean).length;
}

function getReadingTimeMin() {
  return Math.max(1, Math.round(wordCount() / 220));
}

function mediaBlocks(chapterNumber: number, paragraphNumber: number) {
  return chapterMedia
    .filter((media) => media.type === "image" && media.chapterNumber === chapterNumber && media.after === paragraphNumber)
    .map((media) => ({
      type: "image" as const,
      id: `img-ch${media.chapterNumber}-${media.after}`,
      src: media.src,
      alt: media.alt ?? media.caption,
      caption: media.caption,
      wide: media.wide,
    }));
}

function buildBody() {
  return bigScaleChapters.flatMap((chapter) => [
    {
      type: "h" as const,
      id: `chapter-${chapter.number}`,
      level: 2 as const,
      text: chapter.title,
    },
    {
      type: "fieldnote" as const,
      id: `chapter-${chapter.number}-deck`,
      speaker: "The Seer",
      text: chapter.deck,
    },
    ...chapter.paragraphs.flatMap((paragraph, index) => [
      {
        type: "p" as const,
        id: `ch${chapter.number}-p${index + 1}`,
        text: paragraph,
      },
      ...mediaBlocks(chapter.number, index + 1),
    ]),
  ]);
}

function buildScenes() {
  return bigScaleChapters.map((chapter, index) => ({
    id: `scene-chapter-${chapter.number}`,
    startBlockId: `chapter-${chapter.number}`,
    mood: index % 3 === 0 ? ("Wisdom" as const) : ("Neutral" as const),
    label: `Chapter ${chapter.number}: ${chapter.title}`,
    accentOverride: index % 2 === 0 ? "#e0a030" : "#5fb7c4",
  }));
}

export function GET() {
  const body = buildBody();
  const chapters = bigScaleChapters.map((chapter) => ({
    id: `chapter-${chapter.number}`,
    title: chapter.title,
    startBlockId: `chapter-${chapter.number}`,
  }));

  return NextResponse.json({
    schemaVersion: 1,
    id: "big-scale-betrayal",
    number: 2,
    title: "Big Scale Betrayal",
    realm: "The Mortals",
    magnitude: "Novel",
    deity: "Wisdom",
    recordedBy: "The Seer",
    readingTimeMin: getReadingTimeMin(),
    wordCount: wordCount(),
    contentNote: "A mythic fantasy prequel with danger, divine judgment, and palace betrayal.",
    body,
    scenes: buildScenes(),
    ambientTrack: {
      src: "/audio/atmosphere/divine-sanctuary-observatory.mp3",
      format: "mp3",
      loop: true,
      gainDb: -22,
    },
    glossary: [
      {
        key: "heba",
        title: "Heba",
        kind: "mortal",
        blurb: "A merchant's daughter whose gift can weigh the truth of almost any heart.",
      },
      {
        key: "kemet",
        title: "Kemet",
        kind: "term",
        blurb: "The ancient kingdom where market debt, royal power, and divine law collide.",
      },
      {
        key: "sacred-scales",
        title: "The Sacred Scales",
        kind: "term",
        blurb: "Heba's instrument of judgment, where feather, heart, and truth refuse to stay symbolic.",
      },
      {
        key: "god-of-order",
        title: "God of Order",
        kind: "god",
        blurb: "The divine pressure behind Heba's gift, law, and impossible usefulness to power.",
      },
      {
        key: "matu-nefer",
        title: "Matu and Nefer",
        kind: "term",
        blurb: "Armored crocodile guardians of the royal library, loyal to sacred law and very sharp teeth.",
      },
    ],
    keyQuotations: [
      "Love doesn't fix everything.",
      "I cannot judge you.",
      "Destined to sell cabbage.",
    ],
    nextPaths: [
      { label: "Return to the steps", href: "/big-scale-betrayal#big-scale-betrayal", kind: "preserve" },
      { label: "Enter A Court of Foxes", href: "/a-court-of-foxes", kind: "random" },
      { label: "Return to Observations", href: "/observations", kind: "archive" },
    ],
    secondGaze: [
      {
        oid: "ch1-p13",
        note: "Heba says she has weighed her options before the world shows her how literal weighing can become.",
      },
      {
        oid: "ch1-p44",
        note: "The line sounds humble, but the Glass hears a prophecy disguising itself as resignation.",
      },
    ],
    lenses: {},
    chapters,
  });
}
