export const COPY = {
  open: "Open",
  openAria: "Open immersive reading",
  skip: "View",
  skipAria: "View this Observation and begin reading",
  leave: "Leave",
  leaveAria: "Leave immersive reading",
  sound: "Sound",
  soundAria: "Sound and Read Aloud settings",
  soundAriaOpen: "Sound and Read Aloud settings — open",
  focus: "Focus",
  lantern: "Lantern",
  lanternAriaOff: "Lantern — paragraph focus off",
  lanternAriaOn: "Lantern — paragraph focus on",
  lanternPanelAria: "Lantern — light the current paragraph",
  focusMoreAria: "More focus options",
  focusMoreCloseAria: "Close focus options",
  images: "Images",
  imagesAriaOff: "Show story images",
  imagesAriaOn: "Hide story images",
  imagesShownToast: "Images shown.",
  imagesHiddenToast: "Images hidden.",
  text: "Text",
  textAria: "Text appearance settings",
  textAriaOpen: "Text appearance settings — open",
  close: "Close",
  closePanelAria: "Close panel",
  soundPanelAria: "Sound settings",
  soundPaused: "Sound is paused until you turn it on.",
  soundReady: "Choose a focus track, Read Aloud, or silence. Read Aloud follows your voice and highlights the text.",
  soundReadyNoNarration:
    "Choose one of the focus tracks for reading, or turn on Read Aloud to let the Glass follow your voice.",
  soundActive: "Sound is active. The Glass will keep the focus audio gentle while you read.",
  readAloudListeningDescription: "Read Aloud is listening. Read naturally; the Glass will highlight each sentence it recognizes.",
  narrationUnavailable: "Narration isn't available for this record yet.",
  focusTrack: "Focus track",
  focusTrackGroupAria: "Choose reading focus track",
  playMusic: "Play Music",
  pauseMusic: "Pause Music",
  atmosphereAria: "Play selected focus music",
  atmosphereStopAria: "Pause selected focus music",
  atmosphereUnavailableAria: "Focus track unavailable for this record",
  readAloud: "Read Aloud",
  stopReading: "Stop Reading",
  readAloudAria: "Turn on Read Aloud and let the Glass follow your voice",
  readAloudStopAria: "Stop Read Aloud",
  readAloudUnavailableAria: "Read Aloud needs a supported browser and microphone access",
  readAloudIdleStatus: "Your browser will ask for microphone permission. Gaze Glass does not save your voice.",
  readAloudListeningStatus: "Listening now. Start with the sentence in front of you.",
  readAloudUnsupportedStatus: "Read Aloud is not supported in this browser yet.",
  readAloudOnToast: "Read Aloud listening.",
  readAloudOffToast: "Read Aloud stopped.",
  readAloudUnavailableToast: "Read Aloud is not available in this browser yet.",
  readAloudMicBlockedToast: "Microphone permission is needed for Read Aloud.",
  narration: "Narration",
  narrationAria: "Toggle narration",
  narrationUnavailableAria: "Narration unavailable until a voice recording is added",
  mute: "Mute",
  muteAria: "Mute or unmute Observation Mode sound",
  muteUnavailableAria: "Mute unavailable until sound is available",
  atmosphereOnToast: "Focus track on.",
  atmosphereOffToast: "Focus track paused.",
  generatedAtmosphereToast: "Glass atmosphere on.",
  narrationOnToast: "Narration on.",
  narrationPausedToast: "Narration paused.",
  narrationUnavailableToast: "Add a narration file and cues to unlock this voice.",
  mutedToast: "Sound muted.",
  unmutedToast: "Sound unmuted.",
  soundUnavailableToast: "The Glass could not start sound here.",
  focusPanelAria: "Reading focus settings",
  focusModeAria: "Reading focus mode",
  focusDescription: "Choose how the Glass steadies the page while the text remains intact.",
  off: "Off",
  offAria: "No focus aid",
  band: "Band",
  bandAria: "Line band — show 1, 3, or 5 lines",
  ruler: "Ruler",
  rulerAria: "Reading ruler — follow my position",
  spacing: "Spacing",
  spacingAriaOff: "Generous spacing — off",
  spacingAriaOn: "Generous spacing — on",
  textDescription: "Change the atmosphere without moving the prose out of reach.",
  obsidian: "Obsidian",
  obsidianAria: "Obsidian theme — dark background",
  parchment: "Parchment",
  parchmentAria: "Parchment theme — warm light background",
  moonlight: "Moonlight",
  moonlightAria: "Moonlight theme — cool dark background",
  size: "Size",
  sizeGroupAria: "Text size",
  decreaseTextSizeAria: "Decrease text size",
  increaseTextSizeAria: "Increase text size",
  lanternOnToast: "Lantern on",
  lanternOffToast: "Lantern off",
  bandToast: "Band selected.",
  rulerToast: "Ruler selected.",
  focusResetToast: "Focus reset.",
  spacingOnToast: "Spacing on.",
  spacingOffToast: "Spacing off.",
  plateObservation: "Observation",
  recordedBy: "Recorded by the Seer",
  sealed: "The Seer has sealed this record.",
  loadError: "This record couldn't open in the Glass. You can still read it below.",
} as const;
