export const COPY = {
  open: "Open",
  openAria: "Open immersive reading",
  skip: "Begin",
  skipAria: "View this Observation and begin reading",
  leave: "Leave",
  leaveAria: "Leave immersive reading",
  sound: "Sound",
  soundAria: "Sound and Read Aloud settings",
  soundAriaOpen: "Sound and Read Aloud settings — open",
  focus: "Focus",
  lantern: "Lantern",
  lanternAriaOff: "Lantern — paragraph focus off",
  lanternAriaOn: "Lantern — paragraph focus on",
  lanternPanelAria: "Lantern — light the current paragraph",
  focusMoreAria: "More focus options",
  focusMoreCloseAria: "Close focus options",
  images: "Images",
  imagesAriaOff: "Show story images",
  imagesAriaOn: "Hide story images",
  imagesShownToast: "Images shown.",
  imagesHiddenToast: "Images hidden.",
  text: "Text",
  textAria: "Text appearance settings",
  textAriaOpen: "Text appearance settings — open",
  close: "Close",
  closePanelAria: "Close panel",
  soundPanelAria: "Sound settings",
  soundPaused: "Sound is paused until you turn it on.",
  soundReady:
    "Choose a focus track to play, use Read Aloud, or silence the Glass.",
  soundReadyNoNarration:
    "Choose Focus #1 or Focus #2 to start focus audio, or turn on Read Aloud to hear the Glass read with you.",
  soundActive: "Sound is active. The Glass will keep the focus audio gentle while you read.",
  readAloudListeningDescription: "Read Aloud is listening. Read naturally; the Glass will highlight each sentence it recognizes.",
  readAloudPlaybackDescription: "Read Aloud is playing. The Glass will read each sentence and highlight the text as it goes.",
  narrationUnavailable: "Narration isn't available for this record yet.",
  focusTrack: "Play focus track",
  focusTrackGroupAria: "Choose and play reading focus track",
  playMusic: "Play Music",
  pauseMusic: "Pause Music",
  atmosphereAria: "Play selected focus music",
  atmosphereStopAria: "Pause selected focus music",
  atmosphereUnavailableAria: "Focus track unavailable for this record",
  readAloud: "Read Aloud",
  stopReading: "Stop Reading",
  readAloudAria: "Turn on Read Aloud and let the Glass follow your voice",
  readAloudPlaybackAria: "Turn on Read Aloud and hear the Glass read the Observation",
  readAloudStopAria: "Stop Read Aloud",
  readAloudUnavailableAria: "Read Aloud needs a supported browser and microphone access",
  readAloudIdleStatus: "Your browser will ask for microphone permission. Gaze Glass does not save your voice.",
  readAloudPlaybackIdleStatus: "This browser cannot follow your microphone, but it can read the Observation aloud.",
  readAloudListeningStatus: "Listening now. Start with the sentence in front of you.",
  readAloudPlaybackStatus: "Reading aloud now. The Glass is highlighting each sentence as it speaks.",
  readAloudUnsupportedStatus: "Read Aloud is not supported in this browser yet.",
  readAloudOnToast: "Read Aloud listening.",
  readAloudPlaybackOnToast: "Read Aloud playing.",
  readAloudFallbackToast: "Voice following is not available here, so Read Aloud is playing instead.",
  readAloudMicFallbackToast: "Microphone access was blocked, so Read Aloud is playing instead.",
  readAloudOffToast: "Read Aloud stopped.",
  readAloudFinishedToast: "Read Aloud finished.",
  readAloudUnavailableToast: "Read Aloud is not available in this browser yet.",
  readAloudMicBlockedToast: "Microphone permission is needed for Read Aloud.",
  narration: "Narration",
  narrationAria: "Toggle narration",
  narrationUnavailableAria: "Narration unavailable until a voice recording is added",
  mute: "Mute",
  muteAria: "Mute or unmute Observation Mode sound",
  muteUnavailableAria: "Mute unavailable until sound is available",
  atmosphereOnToast: "Focus track on.",
  atmosphereOffToast: "Focus track paused.",
  generatedAtmosphereToast: "Glass atmosphere on.",
  narrationOnToast: "Narration on.",
  narrationPausedToast: "Narration paused.",
  narrationUnavailableToast: "Add a narration file and cues to unlock this voice.",
  mutedToast: "Sound muted.",
  unmutedToast: "Sound unmuted.",
  soundUnavailableToast: "The Glass could not start sound here.",
  focusPanelAria: "Reading focus settings",
  focusModeAria: "Reading focus mode",
  focusDescription: "Choose how the Glass steadies the page while the text remains intact.",
  off: "Off",
  offAria: "No focus aid",
  band: "Band",
  bandAria: "Line band — show 1, 3, or 5 lines",
  ruler: "Ruler",
  rulerAria: "Reading ruler — follow my position",
  spacing: "Spacing",
  spacingAriaOff: "Generous spacing — off",
  spacingAriaOn: "Generous spacing — on",
  textDescription: "Change the atmosphere without moving the prose out of reach.",
  pace: "Pace",
  paceGroupAria: "Story pace mode",
  drift: "Drift",
  driftAria: "Drift pace — spacious pleasure reading",
  focusPace: "Focus",
  focusPaceAria: "Focus pace — steady paragraph support",
  sprint: "Sprint",
  sprintAria: "Sprint pace — tighter reading to finish faster",
  rest: "Rest",
  restAria: "Rest pace — softer reading for tired eyes",
  obsidian: "Obsidian",
  obsidianAria: "Obsidian theme — dark background",
  parchment: "Parchment",
  parchmentAria: "Parchment theme — warm light background",
  moonlight: "Moonlight",
  moonlightAria: "Moonlight theme — cool dark background",
  size: "Size",
  sizeGroupAria: "Text size",
  decreaseTextSizeAria: "Decrease text size",
  increaseTextSizeAria: "Increase text size",
  lanternOnToast: "Lantern on",
  lanternOffToast: "Lantern off",
  bandToast: "Band selected.",
  rulerToast: "Ruler selected.",
  focusResetToast: "Focus reset.",
  spacingOnToast: "Spacing on.",
  spacingOffToast: "Spacing off.",
  driftToast: "Drift pace selected.",
  focusPaceToast: "Focus pace selected.",
  sprintToast: "Sprint pace selected.",
  restToast: "Rest pace selected.",
  plateObservation: "Observation",
  modeName: "Observation Mode",
  modeDescription:
    "Focus is harder than it used to be, even for stories we want to read. This room is built to help — choose your pace, add sound or Read Aloud, and steady each line with Lantern, Band, or Ruler.",
  recordedBy: "Recorded by the Seer",
  sealed: "The Seer has sealed this record.",
  loadError: "This record couldn't open in the Glass. You can still read it below.",
} as const;
